homeassistant:

config:
frontend:
sun:

lovelace:
  mode: yaml
  resources:
    - url: http://127.0.0.1:5000/compass-card.js
      type: module
  dashboards:
    lovelace-yaml:
      mode: yaml
      filename: ui-lovelace.yaml
      title: Compass
      icon: mdi:compass
      show_in_sidebar: true
      require_admin: false

input_number:
  entity:
    name: Entity
    initial: 30
    min: -359.9
    max: 359.9
    step: 1
    unit_of_measurement: °
    icon: mdi:compass
  secondary_entity:
    name: Secondary Entity
    initial: 20.8
    min: 0
    max: 120
    step: 0.1
    unit_of_measurement: km/h
    icon: mdi:weather-windy
