background: var(--background-image)
views:
  - cards:
      - type: entities
        entities:
          - entity: input_number.entity
          - entity: input_number.secondary_entity
        title: Debug sliders
        class: top-level-graph
      - type: custom:compass-card
        name: Number Entity
        entity: input_number.entity
        secondary_entity: input_number.secondary_entity
        direction_offset: 0
        class: top-level-graph
      - type: custom:compass-card
        name: String Entity
        entity: input_text.dir_str
        secondary_entity: input_number.secondary_entity
        direction_offset: 0
        class: top-level-graph
      - type: custom:compass-card
        name: Combined Entity
        entity: input_text.dir_combined
        secondary_entity: input_number.secondary_entity
        direction_offset: 0
        class: top-level-graph
